### ISSUE TITLE
Change the Color of NavBar Items to while 

### ISSUE THREAD

**Issue by Vijaykv5** [MohitSinghChauhan/Namaste-Javascript-Handbook#1]
<img width="1440" alt="Screenshot 2023-09-04 at 3 34 39 PM" src="https://github.com/MohitSinghChauhan/Namaste-Javascript-Handbook/assets/94985341/b7e83b2f-1d91-44af-8d5d-dc578c979502">

The Items in the Navbar is invisible Because its of Dark color
I would Suggest to make it white :)

**Comment by Vijaykv5** [comment]
I would like to work on this issue though :)

**Comment by MohitSinghChauhan** [comment]
Thanks for showing interest @Vijaykv5.

But this is a sub-issue of bigger issue that is fixed now hence this is also fixed.
